version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.5.0

jobs:
  build:
    working_directory: ~/auth-service
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          name: restore-yarn-cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - restore_cache:
          name: restore-node-modules-cache
          key: node-modules{{ checksum "yarn.lock" }}
      - run:
          name: install-dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: save-yarn-cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          name: save-node-modules-cache
          key: node-modules{{ checksum "yarn.lock" }}
          paths:
            - node_modules
          
  lint:
    working_directory: ~/auth-service
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          name: restore-node-modules-cache
          key: node-modules{{ checksum "yarn.lock" }}
      - run:
          name: ls
          command: ls -a
      - run:
          name: lint
          command: yarn lint

  test:
    working_directory: ~/auth-service
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          name: restore-node-modules-cache
          key: node-modules{{ checksum "yarn.lock" }}
      - attach_workspace: { at: '.' }
      - run:
          name: test
          command: yarn test

workflows:
  version: 2.1
  build_test_deploy:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
          repo: '$AWS_ECR_REPO'
          tag: '$CIRCLE_SHA1'
          requires:
            - build
            - test
          filters:
            branches:
              only: development
